name: API CD
on: [push, workflow_dispatch]

jobs:
  Release:
    runs-on: ubuntu-18.04
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      with: 
        fetch-depth: 1
        
    - name: Upload to Server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4 
      with:
        username: 'root'
        server: '${{ secrets.SERVER_IP }}'
        ssh_private_key: '${{ secrets.ACCESS_KEY_SECRET }}'
        remote_path: '/usr/server/api/'
        
    - name: Start running
      uses: garygrossgarten/github-action-ssh@0.7.0
      with:
        command: 'python /usr/server/api/api.py'
        host: ${{ secrets.SERVER_IP }}
        username: 'root'
        privateKey: ${{ secrets.ACCESS_KEY_SECRET }}
