name: API CD
on: push

jobs:
  Release:
    runs-on: ubuntu-18.04
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      with: 
        fetch-depth: 1
        
    - name: list
      run: |
        ls
