name: API CD
on: [push, workflow_dispatch]

jobs:
  Release:
    runs-on: ubuntu-18.04
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      with: 
        fetch-depth: 1
        
    - name: Link to Server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4 
      with:
        username: 'root'
        server: '${{ secrets.SERVER_IP }}'
        ssh_private_key: '${{ secrets.ACCESS_KEY_SECRET }}'
        remote_path: '/usr/server/api/'
        
